#ifndef TEST_TASK_SIMPLE_2D_LIB_INCLUDES_DEFAULTS_HPP_
#define TEST_TASK_SIMPLE_2D_LIB_INCLUDES_DEFAULTS_HPP_

#include <cstdint>


const int32_t DEFAULT_CAMERA_X = 0;
const int32_t DEFAULT_CAMERA_Y = 0;
const uint32_t DEFAULT_CAMERA_SCALE = 1;
const uint32_t DEFAULT_CAMERA_ROLL = 0;

#endif  // TEST_TASK_SIMPLE_2D_LIB_INCLUDES_DEFAULTS_HPP_
